
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mdlanyoka
 */
public class RemoveStudent extends javax.swing.JFrame {

    /**
     * Creates new form RemoveStudent
     */
    public RemoveStudent() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtStudent = new javax.swing.JTextField();
        btnRemove = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        RemoveTable = new javax.swing.JTable();
        lblBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jInternalFrame1.setVisible(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REMOVE STUDENT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 230, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setText("Student ID   ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, 30));

        txtStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentActionPerformed(evt);
            }
        });
        jPanel1.add(txtStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 230, 30));

        btnRemove.setBackground(new java.awt.Color(255, 0, 0));
        btnRemove.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 100, -1));

        RemoveTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Name", "Age", "Grade", "Major"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        RemoveTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(RemoveTable);
        if (RemoveTable.getColumnModel().getColumnCount() > 0) {
            RemoveTable.getColumnModel().getColumn(0).setResizable(false);
            RemoveTable.getColumnModel().getColumn(0).setHeaderValue("Student ID");
            RemoveTable.getColumnModel().getColumn(1).setResizable(false);
            RemoveTable.getColumnModel().getColumn(1).setHeaderValue("Name");
            RemoveTable.getColumnModel().getColumn(2).setResizable(false);
            RemoveTable.getColumnModel().getColumn(2).setHeaderValue("Age");
            RemoveTable.getColumnModel().getColumn(3).setResizable(false);
            RemoveTable.getColumnModel().getColumn(3).setHeaderValue("Grade");
            RemoveTable.getColumnModel().getColumn(4).setResizable(false);
            RemoveTable.getColumnModel().getColumn(4).setHeaderValue("Major");
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 730, 210));

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back-button.png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBackMousePressed(evt);
            }
        });
        jPanel1.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 50));

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
     
        String studentID = txtStudent.getText();
       
       if (studentID.isEmpty()) {
         JOptionPane.showMessageDialog(null, "Please enter a student ID");
         return;
     
       } 
       
        if (!studentID.matches("\\d+")) {
           JOptionPane.showMessageDialog(null, "Student ID should contain only numbers.");
           return;
        }
     
        DefaultTableModel tableModel = (DefaultTableModel) RemoveTable.getModel();
        int rowCount = tableModel.getRowCount();
        int rowIndex = -1;
    
        for (int i = 0; i < rowCount; i++) {
        String id = tableModel.getValueAt(i, 0).toString();
        
        if (id.equals(studentID)) {
            rowIndex = i;
            break;
        }
    }
    
        if (rowIndex == -1) {
            JOptionPane.showMessageDialog(null, "Student with ID " + studentID + " not found");
            return;
    }
    
    int confirmDialog = JOptionPane.showConfirmDialog(null, "Are you sure you want to remove this student?", "Confirm Removal", JOptionPane.YES_NO_OPTION);
    
    if (confirmDialog == JOptionPane.YES_OPTION) {
        tableModel.removeRow(rowIndex);
        
        saveStudentData();
     
        txtStudent.setText("");
    }


}

private void saveStudentData() {
    String filePath = "Students.txt";
    File file = new File(filePath);
    try (PrintWriter writer = new PrintWriter(new BufferedWriter(new FileWriter(file)))) {
        DefaultTableModel tableModel = (DefaultTableModel) RemoveTable.getModel();
        int rowCount = tableModel.getRowCount();
        
        for (int i = 0; i < rowCount; i++) {
            StringBuilder rowData = new StringBuilder();
            
            for (int j = 0; j < tableModel.getColumnCount(); j++) {
                rowData.append(tableModel.getValueAt(i, j));
                
                if (j < tableModel.getColumnCount() - 1) {
                    rowData.append(",");
                }
            }
            
            writer.println(rowData.toString());
            
            txtStudent.setText("");
           
        }
        
        JOptionPane.showMessageDialog(null, "Student record removed successfully!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error occurred while saving student data: " + e.getMessage());
    }

            
        
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
               
    String filePath = "C:\\Users\\Mthobisi Mindset\\Documents\\NetBeansProjects\\Student Management System\\Students.txt";
     File file = new File(filePath);
     
     try
     {
         BufferedReader read = new BufferedReader(new FileReader(file));
 
         //String firstLine = read.readLine().trim();
         
         DefaultTableModel table = (DefaultTableModel)RemoveTable.getModel();
         
         
         Object[] tableLines = read.lines().toArray();
         
         for(int i = 0; i < tableLines.length; i++)
         {
             String line = tableLines[i].toString().trim();
             String[] dataRow = line.split(",");
             table.addRow(dataRow);
             
}
             
     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(null, "Error Occured please Try again!!");
        
         
}
         
    }//GEN-LAST:event_formWindowOpened

    private void txtStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentActionPerformed

    private void RemoveTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveTableMouseClicked
       
        int db = RemoveTable.getSelectedRow(); 
    
    DefaultTableModel myDemo =(DefaultTableModel)RemoveTable.getModel();
    
    txtStudent.setText(myDemo.getValueAt(db,0).toString());
   
    }//GEN-LAST:event_RemoveTableMouseClicked

    private void lblBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMousePressed

      

    }//GEN-LAST:event_lblBackMousePressed

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
      
        MainPage page = new MainPage();
        page.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_lblBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable RemoveTable;
    private javax.swing.JButton btnRemove;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBack;
    private javax.swing.JTextField txtStudent;
    // End of variables declaration//GEN-END:variables
}
